name: lwk-scraping
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi==0.104.1
  - uvicorn==0.24.0
  - sqlalchemy==2.0.23
  - psycopg2-binary==2.9.9
  - python-dotenv==1.0.0
  - pydantic==2.4.2
  - selenium==4.6.0
